### ISSUE TITLE
Сделать типы данных в описании API

### ISSUE THREAD

**Issue by ccErrors** [cesbo/help#132]
https://help.cesbo.com/astra/admin-guide/api/session

Тут идея добавить какой-нить пример TS/golang кода описания типа ответа.

Как появилась идея - заполняю таблицу в супобазе куда будут сливаться данные по сессиям и непонятно `client_id — unique session identifier` он какой тип имеет? Судя по 
```
"client_id": N,
"channel_id": "...",
```
 он string

**Comment by ccErrors** [comment]
@and-cesbo как думаешь?

**Comment by and-cesbo** [comment]
> @and-cesbo как думаешь?

проще оставить как есть. поправил, тут опечатка.
у астры в доке `N` - число, `"..."` - строка.
у альты уже по нормальному, с JSON схемой и прочим.
