### ISSUE TITLE
astra: ДОПОЛНИТЬ web-interface/address-format

### ISSUE THREAD

**Issue by ccErrors** [cesbo/help#60]
https://cesbo.com/en/latest/astra/web-interface/address-format

взять форматы оттуда

Параметры источников:

- #111
- #49 

Общие параметры (в раздел processing)

- #112
- #113

**Comment by and-cesbo** [comment]
эта статья довольно безумна. главная цель резделить всё на отдельные статьи по каждому типу входа/выхода.
