### ISSUE TITLE
astra: api/example

### ISSUE THREAD

**Issue by ccErrors** [cesbo/help#72]
https://cesbo.com/en/latest/astra/api/example

сделать редирект на https://help.cesbo.com/astra/admin-guide

**Comment by and-cesbo** [comment]
я думаю нет смысла в этой статье.
- про "Set image on the stream card" - нужна отдельная статья, я сделал новый скрипт для этого и новый набор плюшек #41 
- остальные примеры лучше в описании методов #48 
- сделать редирект на https://help.cesbo.com/astra/admin-guide

**Comment by ccErrors** [comment]
редерект добавил https://github.com/cesbo/mkdwn-csv/commit/3cd6f3846c9663e93248afbd395f0d41d3639318
